"""
Stock maps shipped with SwegHammer.

Add new maps here and register them in STOCK_MAPS so the front end can
pick them up automatically.
"""

from __future__ import annotations

from .map import Map, Objective, Terrain, TerrainType


def _quincunx_objectives(width: float, height: float) -> tuple:
    """
    Five-objective layout common to most 10e missions (Take and Hold, Crucible,
    Tipping Point, etc.): one in the centre and four equidistant points roughly
    a third of the way in from each board edge.
    """
    cx, cy = width / 2.0, height / 2.0
    inset_x = width * 0.30
    inset_y = height * 0.25
    return (
        Objective(name="Centre",    x=cx, y=cy),
        Objective(name="NW Marker", x=cx - inset_x, y=cy + inset_y),
        Objective(name="NE Marker", x=cx + inset_x, y=cy + inset_y),
        Objective(name="SW Marker", x=cx - inset_x, y=cy - inset_y),
        Objective(name="SE Marker", x=cx + inset_x, y=cy - inset_y),
    )


def _competitive_terrain(width: float, height: float) -> tuple:
    """Build a competitive-density Pariah Nexus terrain layout for a board of the
    given size, EVEN-HANDED by construction via 180-degree rotational symmetry
    about the board centre (so neither deployment zone gets a terrain advantage).

    Reproduces the published competitive standard rather than tuning a metric:
    the Games Workshop Pariah Nexus Tournament Companion ships eight measured
    layouts on a 44 by 60 inch board, each a dense field of large two-storey
    L-shaped ruins (roughly five-to-six inch footprints, which block line of
    sight under the current 10e Ruins rule) plus smaller scatter pieces, placed
    as a central ruin mass with flanking ruins so that there is no clean
    deployment-zone-to-deployment-zone sightline. Our previous stock maps carried
    only three to seven small pieces (about eight percent coverage with little
    line-of-sight blocking), which let table-wide shooters fire across an open
    board and starved advancing armies of cover. Cited as
    `terrain.competitive_pariah_nexus_layout`.

    PRIME-DIRECTIVE / EVEN-HANDED: terrain is faction-neutral. The structure is
    the published competitive pattern (central plus flanking, rotationally
    symmetric); it is NOT tuned to favour or disfavour any faction, and the
    objectives are left exactly where each mission places them. Correct even if
    it moved the metric the wrong way, because it matches the real layouts.

    Seed pieces are defined for one half of the board as
    ``(name, fx, fy, w, h, type)`` where ``fx``/``fy`` are fractions of the board
    (so the pattern scales to 44x60 and 44x90 alike) and ``w``/``h`` are physical
    inches (ruins stay roughly five-to-six inches regardless of board length).
    Each non-central seed is emitted together with its 180-degree partner.
    """
    R = TerrainType.RUIN
    O = TerrainType.OBSCURING
    L = TerrainType.LIGHT_COVER
    # Lower/left-half seeds; partners are generated by 180-degree rotation.
    seeds = (
        # Flanking ruins near the deployment-zone corners (break the long
        # diagonal and edge sightlines). Mirrors cover the opposite corners.
        ("Corner Ruin",     0.07, 0.20, 6.0, 6.0, R),
        ("Corner Ruin",     0.71, 0.18, 6.0, 6.0, R),
        # Mid-field ruins flanking the central mass (break the lateral lanes).
        ("Flank Ruin",      0.25, 0.33, 5.0, 6.0, R),
        ("Flank Ruin",      0.56, 0.30, 5.0, 6.0, R),
        # A ruin sealing the central vertical lane near each deployment zone.
        ("Approach Ruin",   0.43, 0.16, 5.0, 5.0, R),
        # Woods (Obscuring) on the wings for advancing cover.
        ("Flank Wood",      0.03, 0.40, 5.0, 6.0, O),
        # Barricade lines (light cover) ahead of each deployment zone.
        ("Forward Barricade", 0.28, 0.12, 8.0, 2.0, L),
        ("Mid Barricade",   0.10, 0.46, 6.0, 2.0, L),
    )
    out = []
    # A large central ruin mass, self-symmetric about the centre — the spine
    # that denies the dead-centre cross-table sightline.
    cw, ch = 8.0, 8.0
    out.append(Terrain("Central Ruin", width / 2.0 - cw / 2.0,
                       height / 2.0 - ch / 2.0, cw, ch, TerrainType.RUIN))
    for (name, fx, fy, w, h, t) in seeds:
        x, y = fx * width, fy * height
        out.append(Terrain(name, x, y, w, h, t))
        rx, ry = width - x - w, height - y - h
        # Skip a degenerate self-overlapping partner (none here, but guard it).
        if abs(rx - x) < 1e-6 and abs(ry - y) < 1e-6:
            continue
        out.append(Terrain(name + " (mirror)", rx, ry, w, h, t))
    return tuple(out)


COMBAT_PATROL_BASIC = Map(
    name="Combat Patrol - Open Field",
    width=44.0,
    height=60.0,
    objectives=_quincunx_objectives(44.0, 60.0),
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


URBAN_SPRAWL = Map(
    name="Strike Force - Urban Sprawl",
    width=44.0,
    height=90.0,
    objectives=_quincunx_objectives(44.0, 90.0),
    terrain=_competitive_terrain(44.0, 90.0),
    deployment_width=12.0,
)


OPEN_PLAINS = Map(
    name="Combat Patrol - Open Plains",
    width=44.0,
    height=60.0,
    objectives=_quincunx_objectives(44.0, 60.0),
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


# ---------------------------------------------------------------------------
# 10e mission-deployment maps with genuine asymmetry
# ---------------------------------------------------------------------------

CRUCIBLE_OF_BATTLE = Map(
    name="Crucible of Battle",
    width=44.0,
    height=60.0,
    objectives=_quincunx_objectives(44.0, 60.0),
    # Diagonal asymmetry: heavy terrain on the NE-SW diagonal, light on NW-SE.
    # Large ruin top-right, wooded copse mid-left, two short barricade ridges
    # bridging them, one impassable wall blocking centre.
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


def _search_and_destroy_objectives(width: float, height: float) -> tuple:
    """
    Search & Destroy: opposing-corner deployment with terrain massed in the
    NW and SE quadrants. Objectives bias toward those heavy-terrain zones:
    one centre, two NW (deeper into the heavy-terrain zone), two SE.
    """
    cx, cy = width / 2.0, height / 2.0
    return (
        Objective(name="Centre",          x=cx, y=cy),
        Objective(name="NW Inner",        x=width * 0.30, y=height * 0.65),
        Objective(name="NW Outer",        x=width * 0.18, y=height * 0.80),
        Objective(name="SE Inner",        x=width * 0.70, y=height * 0.35),
        Objective(name="SE Outer",        x=width * 0.82, y=height * 0.20),
    )


SEARCH_AND_DESTROY = Map(
    name="Search and Destroy",
    width=44.0,
    height=60.0,
    objectives=_search_and_destroy_objectives(44.0, 60.0),
    # Corner deployment: NW and SE clusters of terrain, central no-man's-land
    # mostly open. Players push out of corners across exposed ground to
    # contest mid-board objectives.
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


def _sweeping_engagement_objectives(width: float, height: float) -> tuple:
    """
    Sweeping Engagement (Strike Force, long-axis): three central objectives
    strung along the long axis plus two corner objectives.
    """
    cx = width / 2.0
    return (
        Objective(name="South Spine",  x=cx,           y=height * 0.30),
        Objective(name="Centre Spine", x=cx,           y=height * 0.50),
        Objective(name="North Spine",  x=cx,           y=height * 0.70),
        Objective(name="NW Corner",    x=width * 0.18, y=height * 0.85),
        Objective(name="SE Corner",    x=width * 0.82, y=height * 0.15),
    )


SWEEPING_ENGAGEMENT = Map(
    name="Sweeping Engagement",
    width=44.0,
    height=90.0,
    objectives=_sweeping_engagement_objectives(44.0, 90.0),
    # Long-axis Strike Force layout: two parallel ruin lines running down the
    # middle channel the fight, woods clusters anchor each short edge.
    terrain=_competitive_terrain(44.0, 90.0),
    deployment_width=12.0,
)


def _take_and_hold_objectives(width: float, height: float) -> tuple:
    """
    Take and Hold (Pariah Nexus mission): 4 objectives in the no-man's-land,
    none on the deployment-zone centre-line. Forces players to push forward
    out of their DZ to score. Classic objective control test.
    """
    cx, cy = width / 2.0, height / 2.0
    return (
        Objective(name="South Centre", x=cx,            y=height * 0.33),
        Objective(name="North Centre", x=cx,            y=height * 0.67),
        Objective(name="West Mid",     x=width * 0.25,  y=cy),
        Objective(name="East Mid",     x=width * 0.75,  y=cy),
    )


TAKE_AND_HOLD = Map(
    name="Take and Hold",
    width=44.0,
    height=60.0,
    objectives=_take_and_hold_objectives(44.0, 60.0),
    # 4 mid-board objectives, no central; classic Pariah Nexus push-forward
    # mission. Light cover scattered across no-man's-land, two large ruins
    # at the wings.
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


def _hammer_and_anvil_objectives(width: float, height: float) -> tuple:
    """
    Hammer and Anvil (Pariah Nexus mission): short-edge deployment with the
    map's long axis running between the deployment zones. 5 objectives
    strung along the long axis. Long travel distance — slow factions
    struggle to project across the map.
    """
    cx = width / 2.0
    return (
        Objective(name="South DZ Edge",  x=cx,           y=height * 0.20),
        Objective(name="South Mid",      x=cx,           y=height * 0.35),
        Objective(name="Centre",         x=cx,           y=height * 0.50),
        Objective(name="North Mid",      x=cx,           y=height * 0.65),
        Objective(name="North DZ Edge",  x=cx,           y=height * 0.80),
    )


HAMMER_AND_ANVIL = Map(
    name="Hammer and Anvil",
    width=44.0,
    height=60.0,
    objectives=_hammer_and_anvil_objectives(44.0, 60.0),
    # Short-edge deployment (DZ width=12.0 on each short edge, leaving a 36"
    # no-man's-land along the long axis). Terrain alternates side-to-side
    # along the long axis to channel movement.
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


def _tipping_point_objectives(width: float, height: float) -> tuple:
    """
    Tipping Point (Pariah Nexus mission): one central objective worth more
    than the rest, four corner-ish objectives at midfield. Forces a fight
    over the centre while contesting four outer points.
    """
    cx, cy = width / 2.0, height / 2.0
    return (
        Objective(name="The Tipping Point", x=cx,           y=cy),
        Objective(name="NW Bastion",        x=width * 0.20, y=height * 0.65),
        Objective(name="NE Bastion",        x=width * 0.80, y=height * 0.65),
        Objective(name="SW Bastion",        x=width * 0.20, y=height * 0.35),
        Objective(name="SE Bastion",        x=width * 0.80, y=height * 0.35),
    )


TIPPING_POINT = Map(
    name="Tipping Point",
    width=44.0,
    height=60.0,
    objectives=_tipping_point_objectives(44.0, 60.0),
    # Central objective surrounded by 4 satellite objectives. Terrain
    # forms a ring around the centre — taking it requires committing
    # through exposed lanes between the ring features.
    terrain=_competitive_terrain(44.0, 60.0),
    deployment_width=12.0,
)


STOCK_MAPS = {
    "combat_patrol":       COMBAT_PATROL_BASIC,
    "open_plains":         OPEN_PLAINS,
    "urban_sprawl":        URBAN_SPRAWL,
    "crucible_of_battle":  CRUCIBLE_OF_BATTLE,
    "search_and_destroy":  SEARCH_AND_DESTROY,
    "sweeping_engagement": SWEEPING_ENGAGEMENT,
    # SC4-D — additional Pariah Nexus mission shapes for eval rotation.
    "take_and_hold":       TAKE_AND_HOLD,
    "hammer_and_anvil":    HAMMER_AND_ANVIL,
    "tipping_point":       TIPPING_POINT,
}

# SC4-D — Pariah Nexus mission rotation. evaluate_vs_meta cycles through
# this list per (faction-pair, seed) so each pair sees variety. Keeps
# `DEFAULT_MAP` (COMBAT_PATROL_BASIC) for one-off battles / tests that
# don't need a curated rotation.
PARIAH_NEXUS_2K_ROTATION: tuple = (
    "crucible_of_battle",   # diagonal asymmetry, 44x60
    "take_and_hold",        # 4 mid-board objectives, no centre
    "hammer_and_anvil",     # short-edge deployment, long-axis fight
    "tipping_point",        # central objective with 4 satellites
    "search_and_destroy",   # opposing corners
)

DEFAULT_MAP = COMBAT_PATROL_BASIC


# ---------------------------------------------------------------------------
# Battle-size tagging (10e battle sizes)
# ---------------------------------------------------------------------------
#
# 10e standard battle sizes:
#   Combat Patrol  500 pts, 30" x 40"
#   Incursion     1000 pts, 44" x 60"
#   Strike Force  2000 pts, 44" x 60"
#   Onslaught     3000 pts, 44" x 90"
#
# Our stock maps don't all match those exact footprints, but we tag each with
# a sensible points range so the front end can auto-select or filter.
MAP_POINTS_RANGE = {
    "combat_patrol":       (250, 1250),   # 44 x 60, ruin + barricade — Combat Patrol / Incursion
    "open_plains":         (500, 2000),   # 44 x 60, sparse terrain — Strike Force friendly
    "urban_sprawl":        (1500, 3500),  # 44 x 90, asymmetric — Strike Force / Onslaught
    "crucible_of_battle":  (750, 2000),   # 44 x 60, diagonal asymmetry — Incursion / Strike Force
    "search_and_destroy":  (750, 2000),   # 44 x 60, corner deployment — Incursion / Strike Force
    "sweeping_engagement": (1500, 3500),  # 44 x 90, long-axis Strike Force — Strike Force / Onslaught
    "take_and_hold":       (750, 2000),   # 44 x 60, 4 mid-board objectives — Strike Force
    "hammer_and_anvil":    (750, 2000),   # 44 x 60, short-edge deployment — Strike Force
    "tipping_point":       (750, 2000),   # 44 x 60, central + 4 satellites — Strike Force
}


def auto_select_map_key(points: float) -> str:
    """Pick the stock map whose recommended range best fits this points budget."""
    candidates = []
    for key, (lo, hi) in MAP_POINTS_RANGE.items():
        if lo <= points <= hi:
            # Prefer the band whose centre is closest to the budget
            centre = (lo + hi) / 2.0
            candidates.append((abs(centre - points), key))
    if candidates:
        return min(candidates)[1]
    # Out-of-range: fall back to the closest band edge
    closest = min(
        MAP_POINTS_RANGE.items(),
        key=lambda kv: min(abs(kv[1][0] - points), abs(kv[1][1] - points)),
    )
    return closest[0]


def maps_fitting(points: float) -> "list[str]":
    """All stock map keys whose recommended range includes `points`."""
    fits = [k for k, (lo, hi) in MAP_POINTS_RANGE.items() if lo <= points <= hi]
    return fits or list(MAP_POINTS_RANGE.keys())
